workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_pro
    environment:
      vars:
        xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: '*'
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Build AAB with Flutter  
        script: |
          cd . && flutter build appbundle --debug
          cd . && flutter build apk --debug
      - name: Build finished successfully
        script: |
          input="pubspec.yaml"

          mkdir -p build-results

          SUB="name: "
          SUB2="version: "

          while IFS= read -r line
          do
            if [[ "$line" == "$SUB"* ]]; then
              _name="${line:6}"
              _name=$(echo "$_name" | tr -d '\r')
            fi
            if [[ "$line" == "$SUB2"* ]]; then
              version="${line:9}"
              version=$(echo "$version" | tr -d '\r')
              version="${version%%+*}"
            fi
          done < "$input"

          export name="${_name}-${version}"

          apk="$name".apk
          aab="$name".aab
          app="$name".app

          echo "$apk"
          echo "$aab"
          echo "$app"

          echo t > build-results/"$apk"
          echo t > build-results/"$aab"
          # echo t > "$app"

          mv "$(pwd)"/build/app/outputs/bundle/debug/app-debug.aab build-results/"$aab"
          mv "$(pwd)"/build/app/outputs/flutter-apk/app-debug.apk build-results/"$apk"

          cd build-results || exit 0
          ls -a
          cd ..
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
